server:
  port: 8502

spring:
  zipkin:
    base-url: http://localhost:9411/
  rabbitmq:
    username: admin
    password: admin
  cloud:
    stream:
      bindings:
        output:
          destination: msqueue
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: localhost:9300
      cluster-name: elasticsearch
    host: localhost
    port: 9300
  datasource:
    url: jdbc:mysql://localhost:3306/microservice-app
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: ticket-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka

